name: UnitTest

on:
  push:
    branches: [master, main, dev]
  pull_request:
    branches: [master, main, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: 

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Run Tests
        run: |
          python fibo.py